Repository git-marvel/commit-guardians-client, pull requests merged in 2024-11, with the labels that each got.

#26 feat: noFound Page UI 작성
  src/app/router.jsx
  src/pages/NotFound/index.jsx
  src/shared/assets/fonts/PixelifySans-VariableFont_wght.ttf
  src/shared/assets/fonts/PretendardVariable.woff2
  src/shared/assets/svg/github-logo.svg
  src/shared/components/Button.jsx
  src/shared/components/Error.jsx
  src/shared/components/Footer.jsx
  src/shared/styles/global.css
  tailwind.config.js
Labels: enhancement

#29 feat: Github respository의 주소 입력에 따른 commit 목록 요청 및 응답 데이터 저장
  src/feature/commit/store/useCommitStore.js
  src/pages/Home/api/getCommitList.js
  src/pages/Home/index.jsx
  src/shared/constants/messages.js
  src/shared/utils/extractGitInfoFromURL.js
Labels: enhancement

#31 feat: 뱃지 UI 만들기및 클립보드 복사 기능
  .gitignore
  package.json
  src/app/router.jsx
  src/features/commitBadge/components/CopyBadge.jsx
  src/features/commitBadge/hooks/useCopyBadge.jsx
  src/features/commitBadge/services/index.js
  src/pages/MyCommitBadge/index.jsx
  src/pages/MyCommitScoreboard/index.jsx
  src/pages/NotFound/index.jsx
  src/shared/components/Badge.jsx
  src/shared/components/Button.jsx
  src/shared/components/SnackBar.jsx
  src/shared/config/index.js
  tailwind.config.js
Labels: enhancement

#32 chore: feature 폴더가 중복되는 문제 해결
  src/features/commit/store/useCommitStore.js
  src/pages/Home/index.jsx
Labels: duplicate

#30 feat: 커밋 변경 내용을 change 단위로 분리
  src/entities/change/changeEntity.js
  src/entities/change/services/index.js
  src/pages/Home/api/getCommitList.js
  src/pages/Home/api/index.js
  src/pages/Home/index.jsx
  src/shared/constants/index.js
  src/shared/constants/messages.js
  src/shared/utils/extractGitInfoFromURL.js
Labels: enhancement

#36 fix: 커밋리스트 api 요청 시 비동기 처리 부분 오류 수정 및 잘못된 토큰 경로 수정
  src/pages/Home/api/index.js
Labels: bug

#37 feat: 커밋 목록들 중, 커밋 퀄리티를 검사할 수 있는 커밋들만 저장하기
  src/entities/commitType/services/index.js
  src/pages/Home/api/index.js
  src/pages/Home/index.jsx
  src/shared/utils/extractGitInfoFromURL.js
Labels: enhancement

#39 refactor: Fetch를 axios로 변경
  package.json
  src/pages/Home/api/index.js
Labels: enhancement

#40 refactor: 검사가능한 커밋들을 명시적인 커밋타입으로 치환하여 커밋엔티티를 반환
  src/entities/change/services/index.js
  src/entities/commit/commitEntity.js
  src/entities/commit/enum/commitFormatStyleEnum.js
  src/entities/commit/enum/commitTypeEnum.js
  src/entities/commit/services/index.js
  src/entities/commitType/services/index.js
  src/pages/Home/api/index.js
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/Home/index.jsx
  src/shared/components/Button.jsx
Labels: enhancement

#43 feat: 대용량 데이터 처리 로직에 대한 응답을 기다리는 동안 보여질 로딩 UI 구현
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/Home/index.jsx
  src/shared/components/Loading.jsx
  tailwind.config.js
Labels: enhancement

#44 feat: 100%인 커밋들 수 / 검사한 모든 커밋들 수 계산하기
  src/entities/score/services/index.js
  src/features/commit/store/useCommitStore.js
  src/pages/Home/api/index.js
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/MyCommitBadge/index.jsx
Labels: enhancement

#46 feat: 커밋 타입이 Remove 인 경우, 커밋 퀄리티점수를 계산하는 로직을 추가
  src/entities/change/changeEntity.js
  src/entities/commit/commitEntity.js
  src/entities/commit/services/scoreRemoveCommitType.js
  src/features/commit/components/CommitValidationMark.jsx
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/Home/index.jsx
Labels: enhancement

#45 feat: 데이터 요청 및 응답에 대한 에러 핸들링 추가
  src/features/githubAPIStatus/api/index.js
  src/features/githubAPIStatus/components/GithubAPIStatus.jsx
  src/features/githubAPIStatus/hooks/useGithubAPIStatus.jsx
  src/pages/Home/api/index.js
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/Home/index.jsx
  src/shared/constants/index.js
  src/shared/error/throwCustomErrorMessage.js
Labels: enhancement

#47 test: 커밋타입 Remove 에 대한 로직 테스트 코드 작성
  src/entities/commit/services/__tests__/scoreRemoveCommitType.test.js
  src/entities/commit/services/scoreRemoveCommitType.js
Labels: test

#50 feat: 커밋 타입이 docs인 커밋의 퀄리티 계산 로직 추가
  src/entities/commit/commitEntity.js
  src/entities/commit/services/index.js
  src/entities/commit/services/scoreDocsCommitType.js
  src/pages/Home/hooks/useValidateCommit.jsx
Labels: enhancement

#51 feat: 커밋타입 test인 커밋의 퀄리티 점수 계산 로직 작성
  src/entities/commit/commitEntity.js
  src/entities/commit/services/scoreTestCommitType.js
Labels: enhancement

#56 design: 막대그래프 최대값 제한 수정 및 홈 레이아웃 개선
  src/pages/Home/index.jsx
  src/shared/components/BarGraph.jsx
Labels: bug

#57 fix: commit author 가 null 일 경우 로직 및 화면 처리
  src/entities/commit/services/index.js
  src/features/commit/components/AvatarValue.jsx
  src/features/commit/components/ChangesValue.jsx
Labels: bug

#59 test: Github repository URL 을 이용하여 커밋 목록을 가져오는 테스트 작성
  src/pages/Home/api/__tests__/api.test.js
  src/pages/Home/api/__tests__/diffPerCommit.mock.js
  src/pages/Home/api/__tests__/mockCommits.mock.js
  src/pages/Home/api/__tests__/mockCommitsToCheck.mock.js
Labels: test

#61 feat: style 체크 로직 작성
  package.json
  src/entities/commit/commitEntity.js
  src/entities/commit/services/scoreStyleCommitType.js
Labels: enhancement

#62 feat: test 커밋타입 키워드 추가
  src/entities/commit/services/scoreTestCommitType.js
Labels: enhancement

#63 feat: docs 커밋 타입 파일 확장자에 .rst 추가
  src/entities/commit/services/__tests__/diffObj.mock.js
  src/entities/commit/services/scoreDocsCommitType.js
Labels: enhancement

#64 test: scoreStyleCommitType 함수에 대한 test 코드 작성
  src/entities/commit/services/__tests__/scoreStyleCommitType.test.js
Labels: test

#65 refactor: docs타입에 대한 로직 최적화
  src/entities/commit/services/scoreDocsCommitType.js
Labels: enhancement

#66 test: test타입 커밋 체크 함수에 대한 테스트 코드 작성
  src/entities/commit/services/__tests__/scoreDocsCommitType.test.js
  src/entities/commit/services/__tests__/scoreTestCommitType.test.js
  src/entities/commit/services/scoreTestCommitType.js
Labels: test

#67 feat: 화면 디자인 및 전체 라우팅 적용
  src/entities/commit/enum/commitTypeEnum.js
  src/features/commit/components/CommitQualityScore.jsx
  src/features/commitBadge/components/CopyBadge.jsx
  src/features/repository/components/RepositoryInputForm.jsx
  src/features/repository/components/RepositoryLinkTag.jsx
  src/pages/Home/components/Title.jsx
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/Home/index.jsx
  src/pages/MyCommitBadge/index.jsx
  src/pages/MyCommitScoreboard/components/ScoreBoardHeader.jsx
  src/pages/MyCommitScoreboard/components/ScoreBoardRow.jsx
  src/pages/MyCommitScoreboard/index.jsx
  src/shared/assets/svg/copy-badge-icon.svg
  src/shared/assets/svg/home-icon.svg
  src/shared/components/Badge.jsx
  src/shared/components/BarGraph.jsx
  src/shared/components/Button.jsx
  src/shared/components/CheckIcon.jsx
  src/shared/components/Footer.jsx
  src/shared/components/HomeButton.jsx
  src/shared/components/Loading.jsx
  src/shared/components/SnackBar.jsx
  tailwind.config.js
Labels: enhancement

#72 feat: 총 점수를 화면에 보여주는 기능 및 commit total score 와 관련된 변수명 변경
  src/entities/score/services/index.js
  src/features/commit/store/useCommitStore.js
  src/features/commitBadge/hooks/useCopyBadge.jsx
  src/features/commitBadge/services/index.js
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/MyCommitBadge/index.jsx
Labels: enhancement, refactor

#73 design: 디테일 페이지에 대한 디자인 수정 (github API status 링크로 이동, 정갈한 디자인)
  src/features/commit/components/CommitQualityScore.jsx
  src/features/commitBadge/hooks/useCopyBadge.jsx
  src/features/githubAPIStatus/components/GithubAPIStatus.jsx
  src/pages/Home/index.jsx
  src/pages/MyCommitScoreboard/components/ScoreBoardRow.jsx
  src/pages/MyCommitScoreboard/index.jsx
  src/shared/components/Footer.jsx
Labels: feat, design

#75 fix: 템플릿 형식 커밋과 GitMoji 사용시, 타입검사가 불가능했던 버그 해결
  src/entities/commit/services/index.js
Labels: fix

#76 feat: 총 점수의 계산 방식 변경
  src/entities/score/services/index.js
Labels: feat

#78 feat: Sha 복사 기능 개선
  src/features/commit/components/SHAValue.jsx
  src/features/commit/components/ShaHoverBox.jsx
  src/features/commit/hooks/useCopiedSha.jsx
Labels: feat

#81 feat: 커밋 formatStyle 도 디테일 화면에서 보여주기
  src/entities/commit/commitEntity.js
  src/entities/commit/services/index.js
  src/features/commit/components/CommitFormatStyleValue.jsx
  src/features/commit/components/CommitMessageValue.jsx
  src/features/commit/hooks/useCheckCommitFormatStyle.jsx
  src/features/commit/store/useCommitStore.js
  src/features/repository/components/RepositoryLinkTag.jsx
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/MyCommitScoreboard/index.jsx
  src/shared/components/HomeButton.jsx
Labels: feat, design

#83 fix: prefix-style 스코프가 존재해도, 타입 검사가능하도록 문제해결 및 simple-text-style 의 splitWith 재검토
  src/entities/commit/enum/commitFormatStyleEnum.js
  src/entities/commit/services/index.js
Labels: fix

#85 feat: 모든 페이지에서도 조사할 커밋갯수가 0이라면, 라우팅 불가능하도록 설정
  src/app/router.jsx
  src/pages/Home/hooks/useValidateCommit.jsx
  src/pages/Home/index.jsx
  src/pages/NotFound/index.jsx
  src/shared/constants/index.js
Labels: feat

#86 feat: 디테일 페이지 컬럼값에 추가 정보를 담은 Tooltip UI 구현
  src/features/commit/components/InfoValue.jsx
  src/features/commit/constants/index.js
  src/pages/MyCommitScoreboard/components/ScoreBoardHeader.jsx
  src/pages/MyCommitScoreboard/components/ScoreBoardRow.jsx
  src/shared/components/InfoIcon.jsx
Labels: feat

#89 fix: 정보표시 아이콘이 아닌 곳에서 마우스 호버됐을 때도 툴팁이 보여지는 문제 해결
  src/features/commit/components/InfoValue.jsx
  src/features/commit/components/ShaHoverBox.jsx
  src/features/commitBadge/components/CopyBadge.jsx
Labels: fix

#91 feat: indexedDB 사용
  package.json
  src/features/commit/store/useCommitStore.js
  src/features/githubAPIStatus/hooks/useGithubAPIStatus.jsx
  src/features/githubAPIStatus/store/useGithubStatusStore.js
  src/pages/Home/api/index.js
  src/pages/Home/hooks/useValidateCommit.jsx
  src/shared/constants/index.js
  src/shared/error/throwCustomErrorMessage.js
Labels: feat

#94 fix: remove타입 점수 계산 로직 수정
  src/entities/commit/services/__tests__/scoreRemoveCommitType.test.js
  src/entities/commit/services/scoreRemoveCommitType.js
Labels: fix

#95 feat: 문서 주석(JSDoc, dartdoc) 수정 시 docs 타입으로 판단
  src/entities/commit/services/scoreDocsCommitType.js
Labels: feat

#96 refactor: remove타입 체크 로직에서 쓰이지 않는 파라미터 삭제
  src/entities/commit/services/__tests__/scoreRemoveCommitType.test.js
  src/entities/commit/services/scoreRemoveCommitType.js
  src/pages/Home/api/index.js
Labels: refactor

#99 feat: 새로고침시에도 이전값을 라우팅하여 볼 수 있는 기능 추가
  src/app/router.jsx
  src/pages/Home/hooks/useValidateCommit.jsx
  src/shared/store/usePersistentStore.js
Labels: feat

#104 fix: 배포 전, 이슈들 해결하기 (뱃지 이미지 로딩, 스타일 개선)
  src/features/commitBadge/components/CopyBadge.jsx
  src/features/commitBadge/services/index.js
  src/shared/components/Footer.jsx
Labels: fix

#106 feat: GitHub API 요청 시 여러 토큰을 분산 사용하여 Rate Limit을 관리하는 로직 구현
  src/pages/Home/api/index.js
  src/shared/api/tokenManager.js
  src/shared/constants/index.js
Labels: feat

#93 feat: virtual scroll 기능 구현
  src/pages/MyCommitScoreboard/hooks/useShowCommitDetails.jsx
  src/pages/MyCommitScoreboard/index.jsx
  src/shared/components/VirtualScroll.jsx
  src/shared/hooks/useWindowScroll.jsx
  src/shared/hooks/useWindowSize.jsx
Labels: feat

#112 refactor: FAQ 컴포넌트 분리
  src/pages/MyCommitBadge/components/Guide.jsx
  src/shared/components/Accordion.jsx
  src/shared/components/PlusMinusIcon.jsx
Labels: refactor

#114 Refactor/component
  src/features/commit/components/AvatarValue.jsx
  src/features/commit/components/ChangesValue.jsx
  src/features/commit/components/CommitFormatStyleValue.jsx
  src/features/commit/components/CommitMessageValue.jsx
  src/features/commit/components/CommitQualityScore.jsx
  src/features/commit/components/CommitTypeValue.jsx
  src/features/commit/components/InfoValue.jsx
  src/features/commit/components/SHAValue.jsx
  src/features/commit/components/ShaHoverBox.jsx
  src/features/commitBadge/components/CopyBadge.jsx
  src/features/githubAPIStatus/components/GithubAPIStatus.jsx
  src/features/repository/components/RepositoryInputForm.jsx
  src/features/repository/components/RepositoryLinkTag.jsx
  src/pages/Home/components/Title.jsx
  src/pages/Home/index.jsx
  src/pages/MyCommitBadge/components/ChartContainer.jsx
  src/pages/MyCommitBadge/components/Guide.jsx
  src/pages/MyCommitBadge/index.jsx
  src/pages/MyCommitScoreboard/components/ScoreBoardHeader.jsx
  src/pages/MyCommitScoreboard/components/ScoreBoardRow.jsx
  src/pages/MyCommitScoreboard/index.jsx
  src/pages/NotFound/index.jsx
  src/shared/components/Accordion.jsx
  src/shared/components/Badge.jsx
  src/shared/components/BarGraph.jsx
  src/shared/components/Button.jsx
  src/shared/components/CheckIcon.jsx
  src/shared/components/CopyIcon.jsx
  src/shared/components/Error.jsx
  src/shared/components/FileIcon.jsx
  src/shared/components/Footer.jsx
  src/shared/components/GithubIcon.jsx
  src/shared/components/HomeButton.jsx
  src/shared/components/HomeIcon.jsx
  src/shared/components/InfoIcon.jsx
  src/shared/components/Loading.jsx
  src/shared/components/SnackBar.jsx
  src/shared/components/VirtualScroll.jsx
Labels: refactor
